import React from 'react';
import {AbsoluteFill,Img,interpolate,staticFile,useCurrentFrame} from 'remotion';
const ramp=(f:number,a:number,b:number,x=0,y=1)=>interpolate(f,[a,b],[x,y],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
const Pic=({src,style={}}:{src:string;style?:React.CSSProperties})=><Img src={staticFile(src)} style={{position:'absolute',width:1280,height:720,...style}}/>;
// Stable rough edge; pass another source without copying the reference treatment.
export const RoughMatte=({children,inset=25,seed=0}:{children:React.ReactNode;inset?:number;seed?:number})=>{const edge=(length:number,reverse=false,offset=0)=>Array.from({length:14},(_,i)=>{const t=i/13;const along=length*(reverse?1-t:t);const depth=inset+Math.sin(i*1.71+seed+offset)*8+Math.sin(i*.63+offset)*6;return [along,depth]});const top=edge(1280).map(([x,d])=>`${x},${d}`).join(' ');const right=edge(720,false,2).map(([y,d])=>`${1280-d},${y}`).join(' ');const bottom=edge(1280,true,4).map(([x,d])=>`${x},${720-d}`).join(' ');const left=edge(720,true,6).map(([y,d])=>`${d},${y}`).join(' ');return <AbsoluteFill style={{background:'#000'}}><svg width={0} height={0}><defs><clipPath id="rough-clip"><polygon points={`${top} ${right} ${bottom} ${left}`}/></clipPath></defs></svg><AbsoluteFill style={{clipPath:'url(#rough-clip)',filter:'blur(.3px)'}}>{children}</AbsoluteFill></AbsoluteFill>};
// Layered radial sampling: deterministic 24-tap outward trail, with a sharp centre.
export const RadialSmear=({children,amount,origin='50% 50%'}:{children:React.ReactNode;amount:number;origin?:string})=><AbsoluteFill style={{overflow:'hidden'}}>{children}{amount>0&&Array.from({length:24},(_,i)=><AbsoluteFill key={i} style={{scale:1+amount*(i+1)/24*.12,transformOrigin:origin,opacity:.045,filter:`blur(${amount*1.5}px)`}}>{children}</AbsoluteFill>)}</AbsoluteFill>;
export const RoughDemo=()=>{const f=useCurrentFrame();return f<7?<Pic src={`rough-frames/${String(f).padStart(3,'0')}.png`}/>:<RoughMatte inset={24} seed={3}><Pic src={`rough-frames/${String(f).padStart(3,'0')}.png`}/></RoughMatte>};
export const ThawDemo=()=>{const f=useCurrentFrame();if(f<3)return <Pic src="thaw-lead.png"/>;const grey=ramp(f,10,27,1,0);const zoom=interpolate(f,[36,37,40,43],[1,1.12,1.22,1.28],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});const blur=f>=50?.85:interpolate(f,[36,37,39,42],[0,1.5,.6,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <AbsoluteFill style={{overflow:'hidden'}}><AbsoluteFill style={{scale:zoom,transformOrigin:'50% 50%'}}><RadialSmear amount={blur}><Pic src="thaw-clean.png" style={{filter:`grayscale(${grey})`}}/><Pic src="thaw-caption.png"/></RadialSmear></AbsoluteFill></AbsoluteFill>};
export const ChromaticSmear=({children,frame,start=9,end=14}:{children:React.ReactNode;frame:number;start?:number;end?:number})=>{const p=ramp(frame,start,end,1,0);return <AbsoluteFill style={{overflow:'hidden',filter:`blur(${p*6}px)`,translate:`${Math.sin(frame*2.7)*p*23}px ${Math.cos(frame*1.9)*p*3}px`,rotate:`${Math.sin(frame)*p*1.3}deg`}}>{children}{p>0&&Array.from({length:12},(_,i)=><AbsoluteFill key={`trail-${i}`} style={{translate:`${-(i+1)*p*9}px 0`,opacity:p*.065}}>{children}</AbsoluteFill>)}{p>0&&[-1,1].map((d)=><AbsoluteFill key={d} style={{mixBlendMode:'screen',opacity:p*.36,translate:`${d*p*28}px 0px`,filter:d<0?'url(#red-channel)':'url(#cyan-channel)'}}>{children}</AbsoluteFill>)}<svg width={0} height={0}><defs><filter id="red-channel"><feColorMatrix type="matrix" values="1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0"/></filter><filter id="cyan-channel"><feColorMatrix type="matrix" values="0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0"/></filter></defs></svg></AbsoluteFill>};
export const RatDemo=()=>{const f=useCurrentFrame();return f<9?<Pic src="rat.png"/>:<RoughMatte inset={24}><ChromaticSmear frame={f}><AbsoluteFill style={{scale:ramp(f,9,15,1.42,1.43),transform:'scaleX(1.07)',translate:`${ramp(f,9,13,0,-140)}px 0`,transformOrigin:'50% 50%',filter:`hue-rotate(${ramp(f,9,20,35,0)}deg) saturate(${ramp(f,9,20,1.65,1)})`}}><Pic src="rat.png"/></AbsoluteFill><Img src={staticFile('rat-label.png')} style={{position:'absolute',left:200,top:500,width:860,height:160}}/></ChromaticSmear></RoughMatte>};
export const FocusCutout=({background,foreground,amount=1}:{background:string;foreground:string;amount?:number})=><AbsoluteFill><Pic src={background} style={{filter:`grayscale(${amount*.5}) blur(${amount*4}px) brightness(${1-amount*.2})`}}/><AbsoluteFill style={{background:'radial-gradient(ellipse 42% 65% at 50% 50%,transparent 10%,black 100%)',opacity:amount*.6}}/><Pic src={foreground}/></AbsoluteFill>;
export const CatDemo=()=>{const f=useCurrentFrame();return <AbsoluteFill><AbsoluteFill style={{filter:f>=19?'blur(3px)':''}}><Pic src="cat-first.png"/>{f>=6&&<AbsoluteFill style={{opacity:ramp(f,6,13)}}><FocusCutout background="cat-back.png" foreground="cat-cutout.png" amount={.15}/></AbsoluteFill>}</AbsoluteFill>{f>=6&&<Img src={staticFile('cat-label.png')} style={{position:'absolute',left:370,top:548,width:540,height:68,scale:ramp(f,6,14,.35,1),filter:f>=19?'blur(3px)':''}}/>}{f>=19&&<Img src={staticFile('cat-meme.png')} style={{position:'absolute',left:475,top:185,width:325,height:355,scale:ramp(f,19,25,.93,1.04)}}/>}</AbsoluteFill>};
export const InventoryPunch=({frame,panel,background,tooltip}:{frame:number;panel:string;background:string;tooltip:string})=>{const p=ramp(frame,7,14);const blur=frame<8?0:interpolate(frame,[8,10,15],[.55,.6,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <AbsoluteFill style={{overflow:'hidden'}}><AbsoluteFill style={{scale:interpolate(frame,[7,8,10,13,14,17],[1.002,1.078,1.204,1.39,1.439,1.439],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}),transformOrigin:'75% 50%'}}><RadialSmear amount={blur}><Pic src={background}/></RadialSmear></AbsoluteFill>{frame>=8&&<Img src={staticFile(tooltip)} style={{position:'absolute',left:455,top:265,width:460,height:215,scale:ramp(frame,8,15,.68,1),filter:`blur(${blur*3}px)`}}/>}</AbsoluteFill>};
const InventoryLabel=({frame}:{frame:number})=><svg width={1280} height={720} style={{position:'absolute',filter:'drop-shadow(2px 5px 2px #000)'}}><defs><linearGradient id="item-text" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#cdfa66"/><stop offset="48%" stopColor="#e4efbd"/><stop offset="52%" stopColor="#e728ff"/><stop offset="100%" stopColor="#a000be"/></linearGradient></defs><text x={640} y={frame<8?610:565} textAnchor="middle" fontFamily="Georgia,serif" fontWeight={700} fontSize={frame<8?83:ramp(frame,8,17,60,92)} fill={frame<8?'url(#item-text)':'#b8e85d'} stroke="#222" strokeWidth={1}>GAMER SUPPS</text>{frame>=8&&<text x={640} y={649} textAnchor="middle" fontFamily="Georgia,serif" fontWeight={700} fontSize={ramp(frame,8,17,60,92)} fill="#d800e8" stroke="#210025" strokeWidth={1}>{frame<29?'ENERGY':'ENERGY DRINKS'}</text>}</svg>;
export const UiDemo=()=>{const f=useCurrentFrame();return <AbsoluteFill><InventoryPunch frame={f} panel="ui-panel.png" background="ui-base.png" tooltip="ui-tooltip.png"/><InventoryLabel frame={f}/></AbsoluteFill>};
